### ISSUE TITLE
How to train own mode on EfficientNet

### ISSUE THREAD

**Issue by syedmustafa54** [WongKinYiu/PartialResidualNetworks#3]
Hello @WongKinYiu I want to train custom on EfficientNet any doc would be helpful

**Comment by WongKinYiu** [comment]
first, using "darknet.exe partial enet-coco.cfg.txt enet-coco.weights enet-coco.conv.131 131" to get coco pre-trained weight of EfficientNet backbone.

Then, Following https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects to modify your custom cfg file.

Note that you should re-calculate anchors of your custom dataset.
